const initialBooks = [
  {
    id: "1",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    image: "",
    publisher: "J. B. Lippincott & Co.",
    publicationYear: 1960,
    genre: "roman",
    copiesAvailable: 3,
  },
  {
    id: "2",
    title: "The Catcher in the Rye",
    author: "J. D. Salinger",
    image: "",
    publisher: "Little, Brown and Company",
    publicationYear: 1951,
    genre: "roman",
    copiesAvailable: 2,
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    image: "",
    publisher: "Secker & Warburg",
    publicationYear: 1949,
    genre: "znanstvena_fantastika",
    copiesAvailable: 5,
  },
  {
    id: "4",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    image: "",
    publisher: "Charles Scribner's Sons",
    publicationYear: 1925,
    genre: "roman",
    copiesAvailable: 4,
  },
  {
    id: "5",
    title: "Brave New World",
    author: "Aldous Huxley",
    image: "",
    publisher: "Chatto & Windus",
    publicationYear: 1932,
    genre: "znanstvena_fantastika",
    copiesAvailable: 3,
  },
];

export default initialBooks;
